PREDICATE_DESCRIPTIONS = [
    {
        "predicate": "synergistic_interaction",
        "object": "drug",
        "subject": "drug",
        "definition": "When two drugs interact in a way that their combined effect is greater than the sum of their individual effects.",
    },
    {
        "predicate": "expression_present",
        "object": "anatomy",
        "subject": "gene_or_protein",
        "definition": "The process in which a gene's sequence is converted into a mature gene product (protein or RNA). This includes the production of an RNA transcript and its processing, as well as translation and maturation for protein-coding genes.",
    },
    {
        "predicate": "ppi",
        "object": "gene_or_protein",
        "subject": "gene_or_protein",
        "definition": "Temporary, non-covalent binding between protein molecules. Protein-protein interactions occur as a result of intermolecular physical forces and spatial complementation between domains or motifs. This interaction can be either homotypic or heterotypic and effect protein structure, conformation, and function.",
    },
    {
        "predicate": "phenotype_present",
        "object": "disease",
        "subject": "effect_or_phenotype",
        "definition": 'phenotype is "The assemblage of traits or outward appearance of an individual. It is the product of interactions between genes and between genes and the environment." phenotype present means a specific phenotype is observed',
    },
    {
        "predicate": "interacts_with",
        "object": "biological_process",
        "subject": "gene_or_protein",
        "definition": "Gene/protein participates in a biological process. (interactions like up/down regulates, is involved in)",
    },
    {
        "predicate": "parent_child",
        "object": "biological_process",
        "subject": "biological_process",
        "definition": '"is a " relation: Indicates that one entity is a subtype or specific instance of another.',
    },
    {
        "predicate": "interacts_with",
        "object": "cellular_component",
        "subject": "gene_or_protein",
        "definition": "A gene/protein is located in a cellular component // Gene/protein is located in or interacts with a cellular component.",
    },
    {
        "predicate": "associated_with",
        "object": "disease",
        "subject": "gene_or_protein",
        "definition": "Suggests a relationship or correlation between a gene/protein and a disease.",
    },
    {
        "predicate": "interacts_with",
        "object": "gene_or_protein",
        "subject": "molecular_function",
        "definition": "A gene/protein has a specific molecular function",
    },
    {
        "predicate": "side_effect",
        "object": "drug",
        "subject": "effect_or_phenotype",
        "definition": "The term was used in various ways in the past, to describe unintended effects of medical intervention, usually negative (unfavourable), but also positive (favourable) ones. It is recommended that this term no longer be used and particularly should not be regarded as synonymous with adverse event or adverse reaction.",
    },
    {
        "predicate": "parent_child",
        "object": "disease",
        "subject": "disease",
        "definition": '"is a " relation: Indicates that one entity is a subtype or specific instance of another.',
    },
    {
        "predicate": "interacts_with",
        "object": "gene_or_protein",
        "subject": "pathway",
        "definition": "The gene or protein participates in the pathway.",
    },
    {
        "predicate": "parent_child",
        "object": "effect_or_phenotype",
        "subject": "effect_or_phenotype",
        "definition": '"is a " relation: Indicates that one entity is a subtype or specific instance of another.',
    },
    {
        "predicate": "contraindication",
        "object": "disease",
        "subject": "drug",
        "definition": "A symptom or medical condition that makes a particular treatment or procedure inadvisable because a person is likely to have a bad reaction.[NCIT]\n'A contraindication is a disposition that increases the risk of harm involved in using a particular drug, carrying out a medical procedure, or engaging in a particular activity such that the risk of harm exceeds a threshold. An contraindication serves as a reason to withhold a certain medical treatment.",
    },
    {
        "predicate": "parent_child",
        "object": "anatomy",
        "subject": "anatomy",
        "definition": '"is a " relation: Indicates that one entity is a subtype or specific instance of another.',
    },
    {
        "predicate": "parent_child",
        "object": "molecular_function",
        "subject": "molecular_function",
        "definition": '"is a " relation: Indicates that one entity is a subtype or specific instance of another.',
    },
    {
        "predicate": "expression_absent",
        "object": "anatomy",
        "subject": "gene_or_protein",
        "definition": "a negative regulation process that inhibits gene expression level",
    },
    {
        "predicate": "target",
        "object": "drug",
        "subject": "gene_or_protein",
        "definition": "A material entity, such as native (gene product) protein, protein complex, microorganism, DNA , etc., that physically interacts with a therapeutic or prophylactic drug (with some binding affinity) and where this physical interaction is (at least partially) the cause of a (detectable) clinical effect.",
    },
    {
        "predicate": "parent_child",
        "object": "cellular_component",
        "subject": "cellular_component",
        "definition": '"is a " relation: Indicates that one entity is a subtype or specific instance of another.',
    },
    {
        "predicate": "indication",
        "object": "disease",
        "subject": "drug",
        "definition": "Description or common names of diseases that the drug is used to treat.",
    },
    {
        "predicate": "enzyme",
        "object": "drug",
        "subject": "gene_or_protein",
        "definition": "Gene/protein encodes an enzyme that metabolizes the drug. \nDrug Metabolism: A series of chemical modifications of a drug compound by enzymatic activity that make the substrate (drug) more water soluble to allow its clearance from the body. Drug metabolism occurs in two phases: Phase I (biotransformation) involves oxidation, hydroxylation reduction, and hydrolysis. Phase II (conjugation) involves synthesis and conjugation.",
    },
    {
        "predicate": "parent_child",
        "object": "pathway",
        "subject": "pathway",
        "definition": '"is a " relation: Indicates that one entity is a subtype or specific instance of another.',
    },
    {
        "predicate": "parent_child",
        "object": "exposure",
        "subject": "exposure",
        "definition": '"is a " relation: Indicates that one entity is a subtype or specific instance of another.',
    },
    {
        "predicate": "associated_with",
        "object": "effect_or_phenotype",
        "subject": "gene_or_protein",
        "definition": "Suggests a relationship or correlation between a gene/protein and a phenotype.",
    },
    {
        "predicate": "transporter",
        "object": "drug",
        "subject": "gene_or_protein",
        "definition": 'Integral membrane proteins that transport molecules or ions into or out of the cell or compartment.\nA protein that is involved in the directed movement of substances into, out of, within or between cells.\n "transport protein" is an umbrella term for e.g. carrier proteins, channel proteins and protein pumps',
    },
    {
        "predicate": "off_label_use",
        "object": "disease",
        "subject": "drug",
        "definition": "The use of an FDA-approved device, drug, or treatment for a purpose other than that for which it was approved.",
    },
    {
        "predicate": "linked_to",
        "object": "disease",
        "subject": "exposure",
        "definition": "Suggests a relationship or correlation between an exposure and a disease.",
    },
    {
        "predicate": "interacts_with",
        "object": "biological_process",
        "subject": "exposure",
        "definition": "The biological process is affected/caused by the exposure.",
    },
    {
        "predicate": "interacts_with",
        "object": "exposure",
        "subject": "gene_or_protein",
        "definition": "The exposure affects/causes a change in the gene or protein.",
    },
    {
        "predicate": "phenotype_absent",
        "object": "disease",
        "subject": "effect_or_phenotype",
        "definition": "Indicates that a specific phenotype is not observed in the context of a disease.",
    },
    {
        "predicate": "carrier",
        "object": "drug",
        "subject": "gene_or_protein",
        "definition": "Proteins that bind or transport specific substances in the blood, within the cell, or across cell membranes.",
    },
    {
        "predicate": "interacts_with",
        "object": "exposure",
        "subject": "molecular_function",
        "definition": "A gene/protein has a specific molecular function",
    },
    {
        "predicate": "interacts_with",
        "object": "cellular_component",
        "subject": "exposure",
        "definition": "The cellular component is affected by the exposure.",
    },
]
